//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Code.Code.Libaries.Net;

namespace Code.Libaries.Net.Packets.ForServer
{
    public enum EventType
    {
        CLICK
    }
    public class UIInterfaceEvent : BasePacket
    {
        public int interfaceId = -1;
        public EventType _eventType;
        public int controlID;

        #region implemented abstract members of BasePacket

        protected override int GetOpCode()
        {
            return 30;
        }

        protected override void enSerialize(ByteStream bytestream)
        {
            bytestream.addShort(interfaceId);
            bytestream.addShort(controlID);
            bytestream.addByte((int)_eventType);
        }

        protected override void deSerialize(ByteStream bytestream)
        {
            interfaceId = bytestream.getUnsignedShort();
            controlID = bytestream.getUnsignedShort();
            _eventType = (EventType) bytestream.getUnsignedByte();
        }

        #endregion
    }
}

