//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Code.Code.Libaries.Net;
using Code.Core.Client.UI;

namespace Code.Libaries.Net.Packets.ForServer
{
    

    public class ChatPacket : BasePacket
    {

        public enum ChatType
        {
            GAME, Public, Private, Party
        }

        public ChatType type;
        public int FROM_SERVER_UnitID;
        public string text;

        #region implemented abstract members of BasePacket

        protected override int GetOpCode()
        {
            return 25;
        }

        protected override void enSerialize(ByteStream bytestream)
        {
            bytestream.addByte((int)type);
            bytestream.addShort(FROM_SERVER_UnitID);
            bytestream.addString(text);
        }

        protected override void deSerialize(ByteStream bytestream)
        {
            type = (ChatType)bytestream.getByte();
            FROM_SERVER_UnitID = bytestream.getUnsignedShort();
            text = bytestream.getString();
        }

        #endregion
    }
}

