//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace OldBlood.Code.Libaries.Net.Packets
{
    public class UnitUpdatePacket : BasePacket
    {

        public ByteStream SubPacketData = new ByteStream();

        #region implemented abstract members of BasePacket

        protected override int GetOpCode()
        {
            return 20;
        }

        protected override void enSerialize(ByteStream bytestream)
        {
            bytestream.addShort(SubPacketData.Length);
            bytestream.addBytes(SubPacketData.GetBuffer());
        }

        protected override void deSerialize(ByteStream bytestream)
        {
            int lenght = bytestream.getUnsignedShort();
            SubPacketData.addBytes(bytestream.getSubBuffer(lenght));
        }

        #endregion
    }
}

