//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Code.Code.Libaries.Net.Packets
{
    public class EnterWorldPacket : BasePacket
    {
        public int worldId = -1;
        public int myUnitID = -1;
        public UnityEngine.Vector3 Position;

        #region implemented abstract members of BasePacket

        protected override int GetOpCode()
        {
            return 19;
        }

        protected override void enSerialize(ByteStream bytestream)
        {
            bytestream.addShort(worldId);
            bytestream.addShort(myUnitID);
            bytestream.addPosition6B(Position);
        }

        protected override void deSerialize(ByteStream bytestream)
        {
            worldId = bytestream.getUnsignedShort();
            myUnitID = bytestream.getShort();
            Position = bytestream.getPosition6B();
        }

        #endregion
    }
}

