//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Code.Code.Libaries.Net.Packets
{
    public class UIInventoryInterfacePacket : BasePacket
    {
        public enum PacketType
        {
            ERROR,
            SHOW,
            HIDE,
            SetItem
        }

        public PacketType type {get;set;}
        public int UnitID { get; set; }
        public int Value { get; set; }
        public int X { get; set; }
        public int Y { get; set; }

        #region implemented abstract members of BasePacket

        protected override int GetOpCode()
        {
            return 51;
        }

        protected override void enSerialize(ByteStream bytestream)
        {
            bytestream.addByte((int)type);
            bytestream.addShort(UnitID);
            bytestream.addShort(Value);
            bytestream.addByte(X);
            bytestream.addByte(Y);
        }

        protected override void deSerialize(ByteStream bytestream)
        {
            type = (PacketType) bytestream.getByte();
            UnitID = bytestream.getUnsignedShort();
            Value = bytestream.getShort();
            X = bytestream.getByte();
            Y = bytestream.getByte();
        }

        #endregion
    }
}

