//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
namespace AssemblyCSharp.Code.Libaries.MeshUtils
{
    public static class Combining
    {
        public static void CombineMeshesIntoSkinnedMeshRenderer(List<Mesh> meshes, SkinnedMeshRenderer renderer)
        {
            Mesh combined = new Mesh();

            CombineInstance[] cis = new CombineInstance[meshes.Count];
            int i = 0;

            foreach (var mesh in meshes)
            {
                CombineInstance ci = new CombineInstance();
                ci.mesh = mesh;
                cis[i++] = ci;
            }

            renderer.sharedMesh.CombineMeshes(cis);
        }
    }
}

